URL: https://milelens.com/account/signin  # 測試網址
staging_URL: https://milelens.staging.ainotam.com/account/signin
api_url: https://milelens.com/
images:
 - images/0.jpg
 - images/1.jpg
 - images/2.jpg
 - images/3.jpg
 - images/4.jpg
 - images/5.jpg
 - images/6.jpg
 - images/7.jpg
num: 800
log:
    file_name: test.log      # 輸出日誌文件名
    backup: 5                # 備份名
    console_level: WARNING  # 控制台輸出等級
    file_level: DEBUG       # 文件輸出等級
    pattern: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'  # 輸出格式