
# 數組，等價於[ 'Cat', 'Dog', 'Goldfish' ]
- Cat
- Dog
- Goldfish

# 二維數組，等價於[ [ 'Cat', 'Dog', 'Goldfish' ] ]
-
 - Cat
 - Dog
 - Goldfish

# 對象、數組嵌套 { languages: [ 'Ruby', 'Perl','Python' ] }
languages:
 - Ruby
 - Perl
 - Python

# 對象嵌套 { hash: { name: 'Steve', foo: 'bar' } }
hash:
 name: Steve
 foo: bar
hash: { name: Steve, foo: bar }    # { hash: { name: 'Steve', foo: 'bar' } }

# 字符串
str: name1     # { str: 'name1' }   字符串默認不使用引號表示。
str: 'key： value'   # { str: 'key: value' }  如果字符串之中包含空格或特殊字符，需要放在引號之中。
str: '內容\n字符串' # { str: '內容\\n字符串'}   單引號會對轉義字符
str: "內容\n字符串"  # { str: '內容\n字符串' }  雙引號不會對轉義字符
str: 'labor''s day'  # { str: 'labor\'s day' }   單引號之中如果還有單引號，必須連續使用兩個單引號轉義。
str: 這是一段
  多行
  字符串           # { str: '這是一段 多行 字符串' }    字符串可以寫成多行，從第二行開始，必須有一個單空格縮進。換行符會被轉為空格。

# 多行字符串可以使用|保留換行符  等價於{ str: 'Foo\nBar\n'}
#+表示保留縮進塊末尾的換行，-表示刪除字符串末尾的換行。 等價於{ str: 'Foo\nBar'}
str: |-
  Foo
  Bar

# 可以使用>折疊換行  下面的等價於{str: 'Foo Bar\n' }
str: >
  Foo
  Bar

#字符串之中可以插入 HTML 標記。 { message: '\n<p style="color: red">\n  段落\n</p>\n' }
message: |

  <p style="color: red">
    段落
  </p>

number: 12.30       # { number: 12.30 }
isSet: true   #{ isSet: true }
parent: ~    # { parent: null }
date: 1976-07-31    #{ date: new Date('1976-07-31') }
e: !!str 123   # { e: '123'}   YAML 允許使用兩個感嘆號，強制轉換數據類型。
f: !!str true  # { f: 'true'}  YAML 允許使用兩個感嘆號，強制轉換數據類型。